/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sponsor;
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import java.awt.FlowLayout;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import java.util.List;
public class CautaSponsorApp extends javax.swing.JFrame {

    /**
     * Creates new form CautaSponsorApp
     */
    public CautaSponsorApp() {
        try {
			employeeDAO = new SponsorDATA();
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
		}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        NumeSponsorTextField = new javax.swing.JTextField();
        CautaButton = new javax.swing.JButton();
        AdaugaSponsorButton = new javax.swing.JButton();
        UpdateSponsorButton = new javax.swing.JButton();
        DeleteSponsorButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduceti Numele Sponsorului");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        NumeSponsorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeSponsorTextFieldActionPerformed(evt);
            }
        });

        CautaButton.setText("Cauta");
        CautaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautaButtonActionPerformed(evt);
            }
        });

        AdaugaSponsorButton.setText("Adauga Sponsor");
        AdaugaSponsorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaSponsorButtonActionPerformed(evt);
            }
        });

        UpdateSponsorButton.setText("Update Sponsor");
        UpdateSponsorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSponsorButtonActionPerformed(evt);
            }
        });

        DeleteSponsorButton.setText("Delete Sponsor");
        DeleteSponsorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSponsorButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 172, Short.MAX_VALUE)
                .addComponent(AdaugaSponsorButton)
                .addGap(53, 53, 53)
                .addComponent(UpdateSponsorButton)
                .addGap(58, 58, 58)
                .addComponent(DeleteSponsorButton)
                .addGap(110, 110, 110)
                .addComponent(CancelButton)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(NumeSponsorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CautaButton)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumeSponsorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CautaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AdaugaSponsorButton)
                        .addComponent(UpdateSponsorButton)
                        .addComponent(DeleteSponsorButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeSponsorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeSponsorTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NumeSponsorTextFieldActionPerformed

    private void CautaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautaButtonActionPerformed
        // TODO add your handling code here:
        try {
					String lastName = NumeSponsorTextField.getText();

					List<Sponsor> employees = null;

					if (lastName != null && lastName.trim().length() > 0) {
						employees = employeeDAO.searchSponsor(lastName);
					} else {
						employees = employeeDAO.getAllSponsor();
					}
					
					// create the model and update the "table"
					SponsorTableModel model = new SponsorTableModel(employees);
					
					table.setModel(model);
					
					/*
					for (Employee temp : employees) {
						System.out.println(temp);
					}
					*/
				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaSponsorApp.this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
				}
        
        
    }//GEN-LAST:event_CautaButtonActionPerformed

    private void AdaugaSponsorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaSponsorButtonActionPerformed
        // TODO add your handling code here:
        SponsorDialog dialog = new SponsorDialog(CautaSponsorApp.this, employeeDAO);

				// show dialog
				dialog.setVisible(true);
        
    }//GEN-LAST:event_AdaugaSponsorButtonActionPerformed

    private void UpdateSponsorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSponsorButtonActionPerformed
        // TODO add your handling code here:
        // get the selected item
				int row = table.getSelectedRow();
				
				// make sure a row is selected
				if (row < 0) {
					JOptionPane.showMessageDialog(CautaSponsorApp.this, "Trebuie sa selectati un sponsor", "Error",
							JOptionPane.ERROR_MESSAGE);				
					return;
				}
				
				// get the current employee
				Sponsor tempSponsor = (Sponsor) table.getValueAt(row, SponsorTableModel.OBJECT_COL);
				
				// create dialog
				SponsorDialog dialog = new SponsorDialog(CautaSponsorApp.this, employeeDAO, 
															tempSponsor, true);

				// show dialog
				dialog.setVisible(true);
        
    }//GEN-LAST:event_UpdateSponsorButtonActionPerformed

    private void DeleteSponsorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSponsorButtonActionPerformed
        // TODO add your handling code here:
        
				try {
					// get the selected row
					int row = table.getSelectedRow();

					// make sure a row is selected
					if (row < 0) {
						JOptionPane.showMessageDialog(CautaSponsorApp.this, 
								"Trebuie sa selectati un Sponsor", "Error", JOptionPane.ERROR_MESSAGE);				
						return;
					}

					// prompt the user
					int response = JOptionPane.showConfirmDialog(
							CautaSponsorApp.this, "Delete this sponsor?", "Confirm", 
							JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

					if (response != JOptionPane.YES_OPTION) {
						return;
					}

					// get the current employee
					Sponsor tempEmployee = (Sponsor) table.getValueAt(row, SponsorTableModel.OBJECT_COL);

					// delete the employee
                                        employeeDAO.deleteSponsor(tempEmployee.getSponsorID());
					//employeeDAO.deleteEmployee(tempEmployee.getId());

					// refresh GUI
					refreshSponsorView();

					// show success message
					JOptionPane.showMessageDialog(CautaSponsorApp.this,
							"Sponsor deleted succesfully.", "Sponsor Deleted",
							JOptionPane.INFORMATION_MESSAGE);

				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaSponsorApp.this,
							"Error deleting sponsor: " + exc.getMessage(), "Error",
							JOptionPane.ERROR_MESSAGE);
				}
        
    }//GEN-LAST:event_DeleteSponsorButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
	public void refreshSponsorView() {

		try {
			List<Sponsor> employees = employeeDAO.getAllSponsor();

			// create the model and update the "table"
			SponsorTableModel model = new SponsorTableModel(employees);

			table.setModel(model);
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
		}
		
	}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CautaSponsorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CautaSponsorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CautaSponsorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CautaSponsorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CautaSponsorApp().setVisible(true);
            }
        });
    }

    
    private SponsorDATA employeeDAO;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdaugaSponsorButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CautaButton;
    private javax.swing.JButton DeleteSponsorButton;
    private javax.swing.JTextField NumeSponsorTextField;
    private javax.swing.JButton UpdateSponsorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
