/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jucator;
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import java.awt.FlowLayout;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import java.util.List;



public class CautaJucatorApp extends javax.swing.JFrame {

    /**
     * Creates new form CautaJucatorApp
     */
    public CautaJucatorApp() {
        try {
			employeeDAO = new JucatorDATA();
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
		}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NumeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        CautaButton = new javax.swing.JButton();
        AdaugaJucatorButton = new javax.swing.JButton();
        UpdateJucatorButton = new javax.swing.JButton();
        DeleteJucatorButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduceti Numele Jucatorului");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        CautaButton.setText("Cauta");
        CautaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautaButtonActionPerformed(evt);
            }
        });

        AdaugaJucatorButton.setText("Adauga Jucator");
        AdaugaJucatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaJucatorButtonActionPerformed(evt);
            }
        });

        UpdateJucatorButton.setText("Update Jucator");
        UpdateJucatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateJucatorButtonActionPerformed(evt);
            }
        });

        DeleteJucatorButton.setText("Delete Jucator");
        DeleteJucatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJucatorButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AdaugaJucatorButton)
                .addGap(48, 48, 48)
                .addComponent(UpdateJucatorButton)
                .addGap(54, 54, 54)
                .addComponent(DeleteJucatorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(CautaButton)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CautaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdaugaJucatorButton)
                    .addComponent(UpdateJucatorButton)
                    .addComponent(DeleteJucatorButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CautaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautaButtonActionPerformed
        // TODO add your handling code here:
        try {
					String lastName = NumeTextField.getText();

					List<Jucator> employees = null;

					if (lastName != null && lastName.trim().length() > 0) {
						employees = employeeDAO.searchEchipe(lastName);
					} else {
						employees = employeeDAO.getAllJucator();
					}
					
					// create the model and update the "table"
					JucatorTableModel model = new JucatorTableModel(employees);
					
					table.setModel(model);
					
					/*
					for (Employee temp : employees) {
						System.out.println(temp);
					}
					*/
				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaJucatorApp.this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
				}
        
        
    }//GEN-LAST:event_CautaButtonActionPerformed

    private void AdaugaJucatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaJucatorButtonActionPerformed
        // TODO add your handling code here:
       JucatorDialog dialog = new JucatorDialog(CautaJucatorApp.this, employeeDAO);

				// show dialog
				dialog.setVisible(true);
        
    }//GEN-LAST:event_AdaugaJucatorButtonActionPerformed

    private void UpdateJucatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateJucatorButtonActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
				
				// make sure a row is selected
				if (row < 0) {
					JOptionPane.showMessageDialog(CautaJucatorApp.this, "You must select an jucator", "Error",
							JOptionPane.ERROR_MESSAGE);				
					return;
				}
				
				// get the current employee
				Jucator tempEmployee = (Jucator) table.getValueAt(row, JucatorTableModel.OBJECT_COL);
				
				// create dialog
				JucatorDialog dialog = new JucatorDialog(CautaJucatorApp.this, employeeDAO, 
															tempEmployee, true);

				// show dialog
				dialog.setVisible(true);
        
    }//GEN-LAST:event_UpdateJucatorButtonActionPerformed

    private void DeleteJucatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJucatorButtonActionPerformed
        // TODO add your handling code here:
        try {
					// get the selected row
					int row = table.getSelectedRow();

					// make sure a row is selected
					if (row < 0) {
						JOptionPane.showMessageDialog(CautaJucatorApp.this, 
								"You must select an jucator", "Error", JOptionPane.ERROR_MESSAGE);				
						return;
					}

					// prompt the user
					int response = JOptionPane.showConfirmDialog(
							CautaJucatorApp.this, "Delete this jucator?", "Confirm", 
							JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

					if (response != JOptionPane.YES_OPTION) {
						return;
					}

					// get the current employee
					Jucator tempEmployee = (Jucator) table.getValueAt(row, JucatorTableModel.OBJECT_COL);

					// delete the employee
                                        employeeDAO.deleteJucator(tempEmployee.getJucatorID());
					//employeeDAO.deleteEmployee(tempEmployee.getId());

					// refresh GUI
					refreshEmployeesView();

					// show success message
					JOptionPane.showMessageDialog(CautaJucatorApp.this,
							"Jucator deleted succesfully.", "Jucator Deleted",
							JOptionPane.INFORMATION_MESSAGE);

				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaJucatorApp.this,
							"Error deleting jucator: " + exc.getMessage(), "Error",
							JOptionPane.ERROR_MESSAGE);
				}
        
        
        
    }//GEN-LAST:event_DeleteJucatorButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
    
    public void refreshEmployeesView() {

		try {
			List<Jucator> employees = employeeDAO.getAllJucator();

			// create the model and update the "table"
			JucatorTableModel model = new JucatorTableModel(employees);

			table.setModel(model);
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
		}
		
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CautaJucatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CautaJucatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CautaJucatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CautaJucatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CautaJucatorApp().setVisible(true);
            }
        });
    }
    
    
    private JucatorDATA employeeDAO;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdaugaJucatorButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CautaButton;
    private javax.swing.JButton DeleteJucatorButton;
    private javax.swing.JTextField NumeTextField;
    private javax.swing.JButton UpdateJucatorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
