/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rezultat;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import java.awt.FlowLayout;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import java.util.List;

public class CautaRezultatApp extends javax.swing.JFrame {

    /**
     * Creates new form CautaRezultatApp
     */
    public CautaRezultatApp() {
        try {
			employeeDAO = new RezultatDATA();
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
		}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NumarEtapaTextField = new javax.swing.JTextField();
        CautaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        AdaugaRezultatButton = new javax.swing.JButton();
        UpdateRezultatButton = new javax.swing.JButton();
        DeleteRezultatButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cauta Sponsorul ID");

        CautaButton.setText("Cauta");
        CautaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautaButtonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        AdaugaRezultatButton.setText("Adaua Rezultat");
        AdaugaRezultatButton.setToolTipText("");
        AdaugaRezultatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaRezultatButtonActionPerformed(evt);
            }
        });

        UpdateRezultatButton.setText("Update Rezultat");
        UpdateRezultatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRezultatButtonActionPerformed(evt);
            }
        });

        DeleteRezultatButton.setText("Delete Rezultat");
        DeleteRezultatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRezultatButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(AdaugaRezultatButton)
                        .addGap(35, 35, 35)
                        .addComponent(UpdateRezultatButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteRezultatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(CancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumarEtapaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(CautaButton)))
                .addGap(28, 28, 28))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumarEtapaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CautaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdaugaRezultatButton)
                    .addComponent(UpdateRezultatButton)
                    .addComponent(DeleteRezultatButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CautaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautaButtonActionPerformed
        // TODO add your handling code here:
        try {
					String lastName = NumarEtapaTextField.getText();

					List<Rezultat> employees = null;
                                        //int nr=Integer.parseInt(lastName);
					if (lastName != null && lastName.trim().length() > 0) {
                                            int nr=Integer.parseInt(lastName);
						employees = employeeDAO.searchRezultat(nr);
					} else {
						employees = employeeDAO.getAllRezultate();
					}
                                        //employees = employeeDAO.getAllRezultate();
					
					// create the model and update the "table"
					RezultatTableModel model = new RezultatTableModel(employees);
					
					table.setModel(model);
					
					/*
					for (Employee temp : employees) {
						System.out.println(temp);
					}
					*/
				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaRezultatApp.this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
				}
        
    }//GEN-LAST:event_CautaButtonActionPerformed

    private void AdaugaRezultatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaRezultatButtonActionPerformed
        // TODO add your handling code here:
        RezultatDialog dialog = new RezultatDialog(CautaRezultatApp.this, employeeDAO);

				// show dialog
				dialog.setVisible(true);
        
    }//GEN-LAST:event_AdaugaRezultatButtonActionPerformed

    private void UpdateRezultatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRezultatButtonActionPerformed
        // TODO add your handling code here:
        
				// get the selected item
				int row = table.getSelectedRow();
				
				// make sure a row is selected
				if (row < 0) {
					JOptionPane.showMessageDialog(CautaRezultatApp.this, "You must select an rezultat", "Error",
							JOptionPane.ERROR_MESSAGE);				
					return;
				}
				
				// get the current employee
				Rezultat tempEmployee = (Rezultat) table.getValueAt(row, RezultatTableModel.OBJECT_COL);
				
				// create dialog
				RezultatDialog dialog = new RezultatDialog(CautaRezultatApp.this, employeeDAO, 
															tempEmployee, true);

				// show dialog
				dialog.setVisible(true);
        
    }//GEN-LAST:event_UpdateRezultatButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void DeleteRezultatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRezultatButtonActionPerformed
        // TODO add your handling code here:
        try {
					// get the selected row
					int row = table.getSelectedRow();

					// make sure a row is selected
					if (row < 0) {
						JOptionPane.showMessageDialog(CautaRezultatApp.this, 
								"You must select an Rezultat", "Error", JOptionPane.ERROR_MESSAGE);				
						return;
					}

					// prompt the user
					int response = JOptionPane.showConfirmDialog(
							CautaRezultatApp.this, "Delete this Rezultat?", "Confirm", 
							JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

					if (response != JOptionPane.YES_OPTION) {
						return;
					}

					// get the current employee
					Rezultat tempEmployee = (Rezultat) table.getValueAt(row, RezultatTableModel.OBJECT_COL);

					// delete the employee
                                        employeeDAO.deleteRezultat(tempEmployee.getRezultatID());
					//employeeDAO.deleteEmployee(tempEmployee.getId());

					// refresh GUI
					refreshEmployeesView();

					// show success message
					JOptionPane.showMessageDialog(CautaRezultatApp.this,
							"Rezultat deleted succesfully.", "Rezultat Deleted",
							JOptionPane.INFORMATION_MESSAGE);

				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaRezultatApp.this,
							"Error deleting rezultat: " + exc.getMessage(), "Error",
							JOptionPane.ERROR_MESSAGE);
				}
        
        
    }//GEN-LAST:event_DeleteRezultatButtonActionPerformed

    public void refreshEmployeesView() {

		try {
			List<Rezultat> employees = employeeDAO.getAllRezultate();

			// create the model and update the "table"
			RezultatTableModel model = new RezultatTableModel(employees);

			table.setModel(model);
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
		}
		
	}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CautaRezultatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CautaRezultatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CautaRezultatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CautaRezultatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CautaRezultatApp().setVisible(true);
            }
        });
    }

    
    private RezultatDATA employeeDAO;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdaugaRezultatButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CautaButton;
    private javax.swing.JButton DeleteRezultatButton;
    private javax.swing.JTextField NumarEtapaTextField;
    private javax.swing.JButton UpdateRezultatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
