/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Echipa;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.*;

import javax.swing.JOptionPane;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import java.awt.FlowLayout;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import java.util.List;
import java.util.*;
import java.sql.*;
import java.io.*;
public class InterogariSimple extends javax.swing.JFrame {

    /**
     * Creates new form InterogariSimple
     */
    public InterogariSimple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExecutaButton1 = new javax.swing.JButton();
        ExecutaButton2 = new javax.swing.JButton();
        ExecutaButton3 = new javax.swing.JButton();
        ExecutaButton4 = new javax.swing.JButton();
        ExecutaButton5 = new javax.swing.JButton();
        ExecutaButton6 = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumeEchipaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ComboBox5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ComboBox61 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboBox63 = new javax.swing.JComboBox<>();
        ComboBox62 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExecutaButton1.setText("Executa");
        ExecutaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton1ActionPerformed(evt);
            }
        });

        ExecutaButton2.setText("Executa");
        ExecutaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton2ActionPerformed(evt);
            }
        });

        ExecutaButton3.setText("Executa");
        ExecutaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton3ActionPerformed(evt);
            }
        });

        ExecutaButton4.setText("Executa");
        ExecutaButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton4ActionPerformed(evt);
            }
        });

        ExecutaButton5.setText("Executa");
        ExecutaButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton5ActionPerformed(evt);
            }
        });

        ExecutaButton6.setText("Executa");
        ExecutaButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton6ActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12" }));
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("1. Afisati echipele care au mai putin de ");

        jLabel2.setText("luni de contract cu un sponsor si numele sponsorului");

        jLabel3.setText("2. Afisati Numele si Prenumele jucatorilor care joaca la echipa de club ");

        jLabel4.setText("3. Afisati Numarul de Goluri inscrise de echipele gazda in etapa cu numarul ");

        ComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel5.setText("4. Afisati Numele Echipelor ce au sponsorul ");

        ComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike", "Puma", "Adidas", "Lacoste", "Filati", "Lotto", "Jomma" }));

        jLabel6.setText("5. Afisati jucatorii care joaca la echipe ce au numarul de campionate castigate mai mare decat");

        ComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "15", "10", "5" }));

        jLabel7.setText("impreuna cu echipele de club.");

        jLabel8.setText("6. Afisati Echipele Oaspete cu un numar de goluri mai mare decat");

        ComboBox61.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel9.setText("in etapa ");

        jLabel10.setText("Rezultatul este ordonat dupa numarul de goluri.(cresc/desc)");

        ComboBox63.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "crescator", "descrescator" }));

        ComboBox62.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelButton)
                        .addGap(268, 268, 268))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExecutaButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NumeEchipaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExecutaButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExecutaButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 30, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ExecutaButton5))
                                    .addComponent(ExecutaButton3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(ComboBox61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExecutaButton6)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExecutaButton1)
                    .addComponent(jLabel1)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NumeEchipaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExecutaButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExecutaButton3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExecutaButton4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ExecutaButton5)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ComboBox61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ComboBox62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ComboBox63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ExecutaButton6)))
                .addGap(72, 72, 72)
                .addComponent(CancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExecutaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton1ActionPerformed
        // TODO add your handling code here:
        String s=null;
        //byte b=255; 
        boolean b=true;
        String c_luni;
        c_luni=ComboBox1.getSelectedItem().toString();
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("NumeEchipa");
        model.addColumn("NumeSponsor");  
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("SELECT  E.NumeEchipa,S.NumeSponsor\n" +
"FROM Sponsor S, SponsorEchipa SE,Echipa E\n" +
" WHERE E.EchipaID=SE.EchipaID and SE.SponsorID=S.SponsorID and  SE.LuniDeContract <"+c_luni);
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2) });
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
    }//GEN-LAST:event_ExecutaButton1ActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void ExecutaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton2ActionPerformed
        // TODO add your handling code here:
        String c_nume;
        c_nume=NumeEchipaTextField.getText().toString();
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("Nume");
        model.addColumn("Prenume");
         model.addColumn("NumeEchipa");  
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("select J.Nume, J.Prenume,E.NumeEchipa\n" +
"from Jucator J,Echipa E\n" +
"where J.EchipaID=E.EchipaID and E.NumeEchipa='"+c_nume+"'");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2),myRs.getString(3) });
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
    }//GEN-LAST:event_ExecutaButton2ActionPerformed

    private void ExecutaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton3ActionPerformed
        // TODO add your handling code here:
         String c_etapa;
         c_etapa = ComboBox3.getSelectedItem().toString();
         int t=Integer.parseInt(c_etapa);
         //c_etapa = int.Parse(PComboBox1.getSelectedItem.)
        //c_etapa=int.PComboBox1.getSelectedItem();
        //int t=Integer.parseInt(c_etapa);
        //System.out.println(c_etapa);
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("EchipaGazda");
        model.addColumn("Goluri");  
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("select E.NumeEchipa As EchipaGazda, R.NumarGoluri1 as Goluri\n" +
"from Echipa E, Rezultat R, Etapa Et\n" +
"where Et.NumarEtapa="+t+" and R.EtapaID=Et.EtapaID and R.EchipaID1=E.EchipaID;");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2) });
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
    }//GEN-LAST:event_ExecutaButton3ActionPerformed

    private void ExecutaButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton4ActionPerformed
        // TODO add your handling code here:
        String c_sponsor;
         c_sponsor = ComboBox3.getSelectedItem().toString();
         //int t=Integer.parseInt(c_etapa);
         //c_etapa = int.Parse(PComboBox1.getSelectedItem.)
        //c_etapa=int.PComboBox1.getSelectedItem();
        //int t=Integer.parseInt(c_etapa);
        //System.out.println(c_etapa);
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("NumeEchipa");
        model.addColumn("NumeSponsor");  
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("select E.NumeEchipa As EchipaGazda, R.NumarGoluri1 as Goluri\n" +
"from Echipa E, Rezultat R, Etapa Et\n" +
"where Et.NumarEtapa='"+c_sponsor+"' and R.EtapaID=Et.EtapaID and R.EchipaID1=E.EchipaID;");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2) });
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
    }//GEN-LAST:event_ExecutaButton4ActionPerformed

    private void ExecutaButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton5ActionPerformed
        // TODO add your handling code here:
          String c_camp;
         c_camp = ComboBox5.getSelectedItem().toString();
         int t=Integer.parseInt(c_camp);
         //c_etapa = int.Parse(PComboBox1.getSelectedItem.)
        //c_etapa=int.PComboBox1.getSelectedItem();
        //int t=Integer.parseInt(c_etapa);
        //System.out.println(c_etapa);
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("Nume");
        model.addColumn("Prenume");
        model.addColumn("NumeEchipa");
        
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("SELECT J.Nume, J.Prenume,E.NumeEchipa\n" +
" FROM Jucator J, Echipa E \n" +
" WHERE E.EchipaID = J.EchipaID and CampCastigate>"+c_camp+"");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2),myRs.getString(3) });
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
    }//GEN-LAST:event_ExecutaButton5ActionPerformed

    private void ExecutaButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton6ActionPerformed
        // TODO add your handling code here:
        String cc="DESC";
         String c_camp1;
         c_camp1 = ComboBox61.getSelectedItem().toString();
         int t1=Integer.parseInt(c_camp1);
         String c_camp2;
         c_camp2 = ComboBox62.getSelectedItem().toString();
         int t2=Integer.parseInt(c_camp2);
         String c_camp3;
         c_camp3 = ComboBox63.getSelectedItem().toString();
         if(c_camp3=="descrescator")
        {
            cc="DESC";
        }
        if(c_camp3=="crescator")
        {
            cc="ASC";
        }
         //c_etapa = int.Parse(PComboBox1.getSelectedItem.)
        //c_etapa=int.PComboBox1.getSelectedItem();
        //int t=Integer.parseInt(c_etapa);
        //System.out.println(c_etapa);
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("NumeEchipa");
        model.addColumn("NumarGoluri2");
        
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("select E.NumeEchipa,R.NumarGoluri2\n" +
"from Echipa E,Etapa Et,Rezultat R\n" +
"where E.EchipaID=R.EchipaID2 and Et.EtapaID=R.EtapaID and Et.NumarEtapa="+c_camp1+"\n" +
"group by E.NumeEchipa,R.NumarGoluri2\n" +
"having R.NumarGoluri2>"+c_camp2+" \n" +
"order by R.NumarGoluri2 "+cc+"");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2)});
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_ExecutaButton6ActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
    
    
    private static void close(Connection myConn, Statement myStmt, ResultSet myRs)
			throws SQLException {

		if (myRs != null) {
			myRs.close();
		}

		if (myStmt != null) {
			
		}
		
		if (myConn != null) {
			myConn.close();
		}
	}

	private void close(Statement myStmt, ResultSet myRs) throws SQLException {
		close(null, myStmt, myRs);		
	}
        private void close(ResultSet myRs) throws SQLException {
		close(null, null, myRs);		
	}

	private void close(Statement myStmt) throws SQLException {
		close(null, myStmt, null);		
	}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterogariSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterogariSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterogariSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterogariSimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterogariSimple().setVisible(true);
            }
        });
    }
      private EchipaDAO echipaDAO;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox3;
    private javax.swing.JComboBox<String> ComboBox4;
    private javax.swing.JComboBox<String> ComboBox5;
    private javax.swing.JComboBox<String> ComboBox61;
    private javax.swing.JComboBox<String> ComboBox62;
    private javax.swing.JComboBox<String> ComboBox63;
    private javax.swing.JButton ExecutaButton1;
    private javax.swing.JButton ExecutaButton2;
    private javax.swing.JButton ExecutaButton3;
    private javax.swing.JButton ExecutaButton4;
    private javax.swing.JButton ExecutaButton5;
    private javax.swing.JButton ExecutaButton6;
    private javax.swing.JTextField NumeEchipaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
