/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Echipa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Serdin
 */
public class InterogariComplexe extends javax.swing.JFrame {

    /**
     * Creates new form InterogariComplexe
     */
    public InterogariComplexe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ExecutaButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ExecutaButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ExecutaButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ExecutaButton4 = new javax.swing.JButton();
        CancelButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1.Aceasta interogare afiseaza top");

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7" }));

        jLabel2.setText("tineri Jucatori. ");

        ExecutaButton1.setText("Executa");
        ExecutaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("2.Afisati Jucatorii care au inaltimea peste inaltimea medie a jucatorilor campionatului.");

        ExecutaButton2.setText("Executa");
        ExecutaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("3.Afisati Echipele care au bugetul mai mare decat ");

        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500", "600", "700", "800" }));

        jLabel5.setText("Rezultatul este ordonat ");

        ComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "crescator", "descrescator" }));

        jLabel6.setText("in functie de numarul de sponsori.");

        ExecutaButton3.setText("Executa");
        ExecutaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("4.Afisati Echipele care au mai putin  de");

        ComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8", "9" }));

        jLabel8.setText("luni de contract cu un sponsor");

        ExecutaButton4.setText("Executa");
        ExecutaButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaButton4ActionPerformed(evt);
            }
        });

        CancelButton1.setText("Cancel");
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(ExecutaButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExecutaButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExecutaButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExecutaButton4)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton1)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ExecutaButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ExecutaButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ExecutaButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ExecutaButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(CancelButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExecutaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton1ActionPerformed
        // TODO add your handling code here:
          String s=null;
        //byte b=255; 
        boolean b=true;
        String c_jucatori;
        c_jucatori=ComboBox1.getSelectedItem().toString();
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("Nume");
        model.addColumn("Prenume");
        model.addColumn("Data Nasterii");  
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery(" SELECT a.nume, a.prenume, a.DataNasterii\n" +
"FROM Jucator a WHERE "+c_jucatori+ ">\n" +
"(SELECT count(*)          \n" +
"FROM Jucator        \n" +
" WHERE a.DataNasterii <DataNasterii)");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2), myRs.getString(3) });
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
    }//GEN-LAST:event_ExecutaButton1ActionPerformed

    private void ExecutaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton2ActionPerformed
        // TODO add your handling code here:
          String s=null;
        //byte b=255; 
        
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("Nume");
        model.addColumn("Prenume");
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("select J.Nume,J.Prenume\n" +
"from Echipa E,Jucator J\n" +
"where J.EchipaID=E.EchipaID\n" +
"group by J.Nume,J.Prenume\n" +
"having AVG(J.Inaltime)>(select AVG(Inaltime) from Jucator) ");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2)});
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
    }//GEN-LAST:event_ExecutaButton2ActionPerformed

    private void ExecutaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton3ActionPerformed
       String cc="DESC";
         String c_camp1;
         c_camp1 = ComboBox2.getSelectedItem().toString();
         int t1=Integer.parseInt(c_camp1);
         
         String c_camp3;
         c_camp3 = ComboBox3.getSelectedItem().toString();
         if(c_camp3=="descrescator")
        {
            cc="DESC";
        }
        if(c_camp3=="crescator")
        {
            cc="ASC";
        }
         //c_etapa = int.Parse(PComboBox1.getSelectedItem.)
        //c_etapa=int.PComboBox1.getSelectedItem();
        //int t=Integer.parseInt(c_etapa);
        //System.out.println(c_etapa);
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("NumeEchipa");
        model.addColumn("Buget");
        
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("  select E.NumeEchipa,E.Buget\n" +
"  from Echipa E\n" +
"  where E.Buget>\n"+c_camp1 +
"  order by(select count(SE.SponsorID)  from SponsorEchipa SE where E.EchipaID=SE.EchipaID) " +cc+";");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2)});
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
    }//GEN-LAST:event_ExecutaButton3ActionPerformed

    private void ExecutaButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaButton4ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
          String s=null;
        //byte b=255; 
        boolean b=true;
        String c_luni;
        c_luni=ComboBox1.getSelectedItem().toString();
        Connection myConn=null;
		Statement myStmt = null;
		ResultSet myRs = null;
                DefaultTableModel model = new DefaultTableModel();
                JTable table = new JTable(model);
        model.addColumn("Echipa ID");
        model.addColumn("Nume Echipa");
         
        try {
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url="jdbc:sqlserver://localhost:1433; databaseName=Campionat; user=Serdin; password=12345";
                myConn=DriverManager.getConnection(url);
                     
			myStmt = myConn.createStatement();
			myRs = myStmt.executeQuery("Select E.EchipaID,E.NumeEchipa\n" +
"from Echipa E\n" +
"where exists(select SE.EchipaID  from SponsorEchipa SE\n" +
"where SE.LuniDeContract>"+c_luni+ "and SE.EchipaID=E.EchipaID)");
			
			while (myRs.next()) {
                            
                   
                                 model.addRow(new Object[] { myRs.getString(1), myRs.getString(2)});
                            
				//Echipa tempEchipa = convertRowToEchipa(myRs);
				//list.add(tempEchipa);
			}

			//return list;		
		}
                catch(Exception e){
                    e.printStackTrace();
                }
        
        /*
		finally {
			close(myStmt, myRs);
		}*/
        
    JFrame f = new JFrame();
    f.setSize(300, 300);
    f.add(new JScrollPane(table));
    f.setVisible(true);
        
        
        
    }//GEN-LAST:event_ExecutaButton4ActionPerformed

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterogariComplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterogariComplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterogariComplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterogariComplexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterogariComplexe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JComboBox<String> ComboBox3;
    private javax.swing.JComboBox<String> ComboBox4;
    private javax.swing.JButton ExecutaButton1;
    private javax.swing.JButton ExecutaButton2;
    private javax.swing.JButton ExecutaButton3;
    private javax.swing.JButton ExecutaButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
