/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Echipa;
import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import java.awt.FlowLayout;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.*;
import Sponsor.*;
import Etapa.*;
import EchipaSponsor.*;
import Jucator.*;
import Rezultat.*;

import javax.swing.JOptionPane;

import java.util.List;
public class Meniu extends javax.swing.JFrame {

    /**
     * Creates new form Meniu
     */   
    
    public Meniu() {
        
        try {
			echipaDAO = new EchipaDAO();
                        
					
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
		}

        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        Iesire = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        ActualizareClasamentButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AdaugaEchipa = new javax.swing.JMenuItem();
        AdaugaSponsor = new javax.swing.JMenuItem();
        SponsoriiEchipelor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AdaugaJucator = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AdaugaEtapa = new javax.swing.JMenuItem();
        AdaugaRezultat = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        InterogariSimple = new javax.swing.JMenuItem();
        InterogariComplexe = new javax.swing.JMenuItem();

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Iesire.setText("Iesire");
        Iesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IesireActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table2);

        ActualizareClasamentButton.setText("Actualizare Clasament");
        ActualizareClasamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizareClasamentButtonActionPerformed(evt);
            }
        });

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu1.setText("Echipa");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AdaugaEchipa.setText("Adauga Echipa");
        AdaugaEchipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaEchipaActionPerformed(evt);
            }
        });
        jMenu1.add(AdaugaEchipa);

        AdaugaSponsor.setText("Adauga Sponsor");
        AdaugaSponsor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaSponsorActionPerformed(evt);
            }
        });
        jMenu1.add(AdaugaSponsor);

        SponsoriiEchipelor.setText("Sponsorii Echipelor");
        SponsoriiEchipelor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SponsoriiEchipelorActionPerformed(evt);
            }
        });
        jMenu1.add(SponsoriiEchipelor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jucator");

        AdaugaJucator.setText("Adauga Jucator");
        AdaugaJucator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaJucatorActionPerformed(evt);
            }
        });
        jMenu2.add(AdaugaJucator);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Etapa");

        AdaugaEtapa.setText("Adauga Etapa");
        AdaugaEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaEtapaActionPerformed(evt);
            }
        });
        jMenu4.add(AdaugaEtapa);

        AdaugaRezultat.setText("Adauga Rezultat");
        AdaugaRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaRezultatActionPerformed(evt);
            }
        });
        jMenu4.add(AdaugaRezultat);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Interogari");

        InterogariSimple.setText("Simple");
        InterogariSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterogariSimpleActionPerformed(evt);
            }
        });
        jMenu6.add(InterogariSimple);

        InterogariComplexe.setText("Complexe");
        InterogariComplexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterogariComplexeActionPerformed(evt);
            }
        });
        jMenu6.add(InterogariComplexe);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(ActualizareClasamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Iesire)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ActualizareClasamentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Iesire)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        EchipaDialog dialog = new EchipaDialog();

				// show dialog
				dialog.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void InterogariSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterogariSimpleActionPerformed
        // TODO add your handling code here:
        InterogariSimple dialog=new InterogariSimple();
        dialog.setVisible(true);
    }//GEN-LAST:event_InterogariSimpleActionPerformed

    private void AdaugaEchipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaEchipaActionPerformed
        // TODO add your handling code here:
        CautaEchipaApp ce=new  CautaEchipaApp();
        ce.setVisible(true);
        
    }//GEN-LAST:event_AdaugaEchipaActionPerformed

    private void IesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IesireActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_IesireActionPerformed

    private void ActualizareClasamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizareClasamentButtonActionPerformed
        // TODO add your handling code here:
        try {
					//String NumeEchipa = NumeEchipaTextField.getText();

					List<equip> echipe = null;

					
						echipe = echipaDAO.Campionat();
					
					// create the model and update the "table"
					CampionatTableModel model = new CampionatTableModel(echipe);
					
					table2.setModel(model);
					
					
				} catch (Exception exc) {
					JOptionPane.showMessageDialog(Meniu.this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
				}
        
        
        
        
    }//GEN-LAST:event_ActualizareClasamentButtonActionPerformed

    private void AdaugaSponsorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaSponsorActionPerformed
        // TODO add your handling code here:
        CautaSponsorApp dialog=new CautaSponsorApp();
       
        dialog.setVisible(true);
    }//GEN-LAST:event_AdaugaSponsorActionPerformed

    private void SponsoriiEchipelorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SponsoriiEchipelorActionPerformed
        // TODO add your handling code here:
        CautaEchipaSponsorApp dialog=new CautaEchipaSponsorApp();
        dialog.setVisible(true);
    }//GEN-LAST:event_SponsoriiEchipelorActionPerformed

    private void AdaugaJucatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaJucatorActionPerformed
        // TODO add your handling code here:
        CautaJucatorApp dialog=new CautaJucatorApp();
        dialog.setVisible(true);
    }//GEN-LAST:event_AdaugaJucatorActionPerformed

    private void AdaugaEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaEtapaActionPerformed
        // TODO add your handling code here:
        CautaEtapaApp dialog=new CautaEtapaApp();
        dialog.setVisible(true);
    }//GEN-LAST:event_AdaugaEtapaActionPerformed

    private void AdaugaRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaRezultatActionPerformed
        // TODO add your handling code here:
        CautaRezultatApp dialog=new CautaRezultatApp();
        dialog.setVisible(true);
    }//GEN-LAST:event_AdaugaRezultatActionPerformed

    private void InterogariComplexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterogariComplexeActionPerformed
        // TODO add your handling code here:
        InterogariComplexe dialog=new InterogariComplexe();
        dialog.setVisible(true);
    }//GEN-LAST:event_InterogariComplexeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meniu().setVisible(true);
            }
        });
    }
    
    private EchipaDAO echipaDAO;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizareClasamentButton;
    private javax.swing.JMenuItem AdaugaEchipa;
    private javax.swing.JMenuItem AdaugaEtapa;
    private javax.swing.JMenuItem AdaugaJucator;
    private javax.swing.JMenuItem AdaugaRezultat;
    private javax.swing.JMenuItem AdaugaSponsor;
    private javax.swing.JButton Iesire;
    private javax.swing.JMenuItem InterogariComplexe;
    private javax.swing.JMenuItem InterogariSimple;
    private javax.swing.JMenuItem SponsoriiEchipelor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
