/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Etapa;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;

import java.awt.FlowLayout;

import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import java.util.List;

public class CautaEtapaApp extends javax.swing.JFrame {

    /**
     * Creates new form CautaEtapaApp
     */
    public CautaEtapaApp() {
        try {
			employeeDAO = new EtapaDATA();
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
		}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CautaButton = new javax.swing.JButton();
        NumarEtapaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        AdaugaEtapaButton = new javax.swing.JButton();
        UpdateEtapaButton = new javax.swing.JButton();
        DeleteEtapaButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduceti Numarul Etapei");

        CautaButton.setText("Cauta");
        CautaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautaButtonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        AdaugaEtapaButton.setText("Adauga Etapa");
        AdaugaEtapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaugaEtapaButtonActionPerformed(evt);
            }
        });

        UpdateEtapaButton.setText("Update Etapa");
        UpdateEtapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEtapaButtonActionPerformed(evt);
            }
        });

        DeleteEtapaButton.setText("Delete Etapa");
        DeleteEtapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEtapaButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(AdaugaEtapaButton)
                        .addGap(28, 28, 28)
                        .addComponent(UpdateEtapaButton)
                        .addGap(35, 35, 35)
                        .addComponent(DeleteEtapaButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(NumarEtapaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CautaButton)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CautaButton)
                    .addComponent(NumarEtapaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdaugaEtapaButton)
                    .addComponent(UpdateEtapaButton)
                    .addComponent(DeleteEtapaButton)
                    .addComponent(CancelButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CautaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautaButtonActionPerformed
        // TODO add your handling code here:
        try {
					String lastName = NumarEtapaTextField.getText();

					List<Etapa> employees = null;

					if (lastName != null && lastName.trim().length() > 0) {
                                            int numar=Integer.parseInt(lastName);
						employees = employeeDAO.searchEtape(numar);
					} else {
						employees = employeeDAO.getAllEtape();
					}
					
					// create the model and update the "table"
					EtapaTableModel model = new EtapaTableModel(employees);
					
					table.setModel(model);
					
					/*
					for (Employee temp : employees) {
						System.out.println(temp);
					}
					*/
				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaEtapaApp.this, "Error: " + exc, "Error", JOptionPane.ERROR_MESSAGE); 
				}
        
        
    }//GEN-LAST:event_CautaButtonActionPerformed

    private void AdaugaEtapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaugaEtapaButtonActionPerformed
        // TODO add your handling code here:
        EtapaDialog dialog = new EtapaDialog(CautaEtapaApp.this, employeeDAO);

				// show dialog
	dialog.setVisible(true);
        
    }//GEN-LAST:event_AdaugaEtapaButtonActionPerformed

    private void UpdateEtapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEtapaButtonActionPerformed
        // TODO add your handling code here:
        // get the selected item
				int row = table.getSelectedRow();
				
				// make sure a row is selected
				if (row < 0) {
					JOptionPane.showMessageDialog(CautaEtapaApp.this, "Trebuie sa selectati o etapa", "Error",
							JOptionPane.ERROR_MESSAGE);				
					return;
				}
				
				// get the current employee
				Etapa tempEmployee = (Etapa) table.getValueAt(row, EtapaTableModel.OBJECT_COL);
				
				// create dialog
				EtapaDialog dialog = new EtapaDialog(CautaEtapaApp.this, employeeDAO, 
															tempEmployee, true);

				// show dialog
				dialog.setVisible(true);
			
        
        
    }//GEN-LAST:event_UpdateEtapaButtonActionPerformed

    private void DeleteEtapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEtapaButtonActionPerformed
        // TODO add your handling code here:
        try {
					// get the selected row
					int row = table.getSelectedRow();

					// make sure a row is selected
					if (row < 0) {
						JOptionPane.showMessageDialog(CautaEtapaApp.this, 
								"Trebuie sa selectati o etapa", "Error", JOptionPane.ERROR_MESSAGE);				
						return;
					}

					// prompt the user
					int response = JOptionPane.showConfirmDialog(
							CautaEtapaApp.this, "Stergeti etapa?", "Confirm", 
							JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

					if (response != JOptionPane.YES_OPTION) {
						return;
					}

					// get the current employee
					Etapa tempEmployee = (Etapa) table.getValueAt(row, EtapaTableModel.OBJECT_COL);

					// delete the employee
                                        employeeDAO.deleteEtapa(tempEmployee.getEtapaID());
					//employeeDAO.deleteEmployee(tempEmployee.getId());

					// refresh GUI
					refreshEmployeesView();

					// show success message
					JOptionPane.showMessageDialog(CautaEtapaApp.this,
							"Etapa deleted succesfully.", "Etapa Deleted",
							JOptionPane.INFORMATION_MESSAGE);

				} catch (Exception exc) {
					JOptionPane.showMessageDialog(CautaEtapaApp.this,
							"Error deleting etapa: " + exc.getMessage(), "Error",
							JOptionPane.ERROR_MESSAGE);
				}
        
        
    }//GEN-LAST:event_DeleteEtapaButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

   public void refreshEmployeesView() {

		try {
			List<Etapa> employees = employeeDAO.getAllEtape();

			// create the model and update the "table"
			EtapaTableModel model = new EtapaTableModel(employees);

			table.setModel(model);
		} catch (Exception exc) {
			JOptionPane.showMessageDialog(this, "Error: " + exc, "Error",
					JOptionPane.ERROR_MESSAGE);
		}
		
	}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CautaEtapaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CautaEtapaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CautaEtapaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CautaEtapaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CautaEtapaApp().setVisible(true);
            }
        });
    }
    
    private EtapaDATA employeeDAO;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdaugaEtapaButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CautaButton;
    private javax.swing.JButton DeleteEtapaButton;
    private javax.swing.JTextField NumarEtapaTextField;
    private javax.swing.JButton UpdateEtapaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
